[package]
name = "konfig-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.11"
serde = { version = "1.0.218", features = ["derive"] }
konfig-rust-derive = { path = "../konfig-rust-derive" }
serde_json = "1.0.139"
serde_yaml = "0.9.34+deprecated"
toml = "0.8.20"
